---
name: lib8tion
description: Math functions specifically designed for LED programming
version: 1.0.8
groups:
  - common
code_owners: UncleRus
depends:
  - freertos
thread_safe: N/A
targets:
  - esp32
  - esp32c2
  - esp32c3
  - esp32c5
  - esp32c6
  - esp32c61
  - esp32h2
  - esp32p4
  - esp32s2
  - esp32s3
  - esp8266
license: MIT
copyrights:
  - name: FastLED
    year: 2013
